---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: wayback-archive-1
  description: Archive API for the wayback copy machine
spec:
  type: openapi
  lifecycle: production
  owner: g1
  definition:
    $text: ./openapi.yaml
